name: Build and Test Spring Boot Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: tripdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check NVD_API_KEY secret is set
        run: |
          if [ -z "${{ secrets.NVD_API_KEY }}" ]; then
            echo "❌ NVD_API_KEY secret is missing!"
            exit 1
          else
            echo "✅ NVD_API_KEY secret is set"
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Lint check
        run: mvn spotless:check

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Build, test & verify
        run: mvn clean verify -Dspring.profiles.active=test # -DnvdApiKey=${{ secrets.NVD_API_KEY }}
#        env:
#          OSSINDEX_USER: ${{ secrets.OSSINDEX_USER }}
#          OSSINDEX_PASS: ${{ secrets.OSSINDEX_PASS }}

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Print test coverage percentage
        run: |
          COVERED=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@covered)" target/site/jacoco/jacoco.xml)
          MISSED=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@missed)" target/site/jacoco/jacoco.xml)
          TOTAL=$((COVERED + MISSED))
          PERCENT=$(awk "BEGIN {printf \"%.2f\", ($COVERED/$TOTAL)*100}")
          echo "Test Coverage: $PERCENT%"

      # Run OWASP Dependency-Check to scan for vulnerabilities
#      - name: Run OWASP Dependency-Check
#        run: mvn org.owasp:dependency-check-maven:check -DnvdApiKey=${{ secrets.NVD_API_KEY }}
#        env:
#          OSSINDEX_USER: ${{ secrets.OSSINDEX_USER }}
#          OSSINDEX_PASS: ${{ secrets.OSSINDEX_PASS }}

#      - name: Upload OWASP Dependency-Check report
#        uses: actions/upload-artifact@v4
#        with:
#          name: dependency-check-report
#          path: target/dependency-check-report.*
