name: Build and Push Docker Image on Tag

on:
  push:
    tags:
      - '*'   # triggers on any tag push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: mvn clean verify -Dspring.profiles.active=test

  release:
    needs: ci           # Only runs if CI succeeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/trip-planner-backend-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/trip-planner-backend-app:${{ env.VERSION }}
