name: Spring Boot CI with DB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: tripdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven skipTests
        run: mvn clean install -DskipTests

      - name: Lint check
        run: mvn spotless:check

      - name: Run tests
        run: mvn test -Dspring.profiles.active=test

      - name: Verify
        run: mvn verify -Dspring.profiles.active=test

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
            name: jacoco-report
            path: target/site/jacoco
